version: '3.1'

services:
  angular:
    image: mrsmith9ja/cc-dash:0.0.2
    networks:
      - proxy-tier
    ports:
      - "80:80"
      - "443:443"

networks:
  web:
    driver: "bridge"
  proxy-tier:
    external:
      name: "nginx-proxy"
