version: '3.1'

services:
  angular:
    image: nginx:1.15.3-alpine
    networks:
      - proxy-tier
    volumes:
      - ./config/proxy/angular/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist/client:/usr/share/nginx/html
    ports:
      - "80:80"

networks:
  proxy-tier:
    external:
      name: "nginx-proxy"
