version: '3.1'

services:
  angular:
    build: .
    networks:
      - proxy-tier
    ports:
      - "80:80"
      - "443:443"

networks:
  web:
    driver: "bridge"
  proxy-tier:
    external:
      name: "nginx-proxy"
